[WIP] Webserver documentation Revision
phalcon/docs pull request #1135
Opened 2017-07-23 02:51 UTC by ninjapanzer

###### What am I?
Under review of the webserver-setup documentation I noticed it was a little unfocused and while the configurations were correct they did not contain line documentation.
There were a couple of discrepancies between windows and linux NGINX configurations. So I have combined them and kept the focus on linux with associated support for fast cgi and proxy_pass config.

I have also reordered the file to put the `built-in` server documentation first. No one is going to get to the NGINX or apache configuration until they have something to deploy in the meantime to improve framework adoption promoting the lowest weight runtime should be first.

Better yet this configuration is not platform dependent and should hopefully get users running without working about a server at all initially.

@niden I am looking for your feedback. This is still a WIP regarding the nginx configuration which I want to double check before this is merged.

2017-07-23 02:52 UTC, ninjapanzer commented
This is WIP until I can confirm the NGINX configuration is without errors but the rest of the changes are ready to review.

2017-07-23 21:57 UTC, ninjapanzer commented
I setup a test environment for NGINX to test the combined config and it has been updated to work.

2017-07-24 05:52 UTC, sergeyklay requested changes

2017-07-24 05:52 UTC, sergeyklay commented on en/webserver-setup.md
> +## NGINX
Could you please use common name like `Nginx` (not `NGINX`, `NginX`, etc) :)

2017-07-24 05:52 UTC, sergeyklay commented on en/webserver-setup.md
> +<a href="https://github.com/phalcon/phalcon-devtools/blob/master/templates/.htrouter.php" target="_blank">.htrouter.php</a>
```
[`.htrouter.php`](https://github.com/phalcon/phalcon-devtools/blob/master/templates/.htrouter.php)
```

[`.htrouter.php`](https://github.com/phalcon/phalcon-devtools/blob/master/templates/.htrouter.php)

2017-07-28 23:51 UTC, ninjapanzer commented on en/webserver-setup.md
> +<a href="https://github.com/phalcon/phalcon-devtools/blob/master/templates/.htrouter.php" target="_blank">.htrouter.php</a>
I would prefer to allow this link to target a new tab. If you still disagree I will update it.
Thanks

2017-07-28 23:52 UTC, ninjapanzer commented
I have rebased this branch to remove merge conflicts due to navigation conversion from Markdown to html

2017-07-29 07:39 UTC, sergeyklay approved these changes
Cc: @niden

2017-07-30 15:07 UTC, merged

2017-07-30 15:07 UTC, niden commented
Thank you!