fix  - title of the factory section in config documentation page
phalcon/docs pull request #1226
Opened 2017-08-27 06:36 UTC by hamidrezabstn

2017-08-28 02:20 UTC, ninjapanzer requested changes
Please rebase your branch against upstream/3.2

`git rebase upstream/3.2`

to eliminate this merge commit this introduces.

2017-09-02 07:23 UTC, hamidrezabstn commented
@ninjapanzer  OMG ! Sry about that ! i've fix it! ty

2017-09-02 15:05 UTC, ninjapanzer approved these changes

2017-09-02 15:05 UTC, merged

2017-09-02 15:06 UTC, ninjapanzer commented
Thank you @hamidrezabstn