[3.3] Improved base tutorial
phalcon/docs pull request #1570
Opened 2018-02-23 07:56 UTC by sergeyklay

2018-02-26 17:09 UTC, niden requested changes

2018-02-26 17:09 UTC, niden commented on en/tutorial-base.md
> +
This tutorial will get you started and help create an application that you can extend to address many needs. The code in this tutorial can also be used as a playground to learn other Phalcon specific concepts and ideas.

2018-02-27 07:19 UTC, sergeyklay commented on en/tutorial-base.md
> +
@niden Done

2018-02-27 17:21 UTC, niden approved these changes

2018-02-27 17:21 UTC, merged

2018-02-27 17:21 UTC, niden commented
Thank you!