Update contributions.md
phalcon/docs pull request #1672
Opened 2018-07-04 14:49 UTC by Kaperskyguru

2018-07-04 16:02 UTC, niden commented on en/contributions.md
> +- As part of your report, please include additional informations such as the OS, PHP version, Phalcon version, web server, memory etc.
This should be `information`

2018-07-04 16:03 UTC, niden requested changes

2018-07-04 16:03 UTC, niden commented on en/contributions.md
Same here

2018-07-04 16:03 UTC, niden commented on en/contributions.md
> +If you have any question about how to use Phalcon, please see the [support page][support].
Either use `a question` or `any questions`

2018-07-05 13:43 UTC, Kaperskyguru reviewed
The changes have been made.

2018-07-05 15:34 UTC, niden requested changes

2018-07-05 15:34 UTC, niden commented on en/contributions.md
This needs to be `information`

2018-07-05 15:52 UTC, Kaperskyguru commented on en/contributions.md
Ok... Thanks for your patience

2018-07-05 15:55 UTC, Kaperskyguru reviewed
Done!

2018-07-05 15:57 UTC, niden approved these changes

2018-07-05 15:57 UTC, merged

2018-07-05 15:57 UTC, niden commented
Thank you!!

2018-07-05 16:00 UTC, Kaperskyguru commented
Wow...  That was my first contribution to project and my first PR too...  Thanks for your assistance.

2018-07-05 17:04 UTC, niden commented
Thank you for the contribution! Keep up the good work!