Update cache.md
phalcon/docs pull request #2191
Opened 2019-01-28 21:02 UTC by ruudboon

Xcache is not in Pecl anymore

2019-01-28 23:11 UTC, CameronHall commented
Thanks @ruudboon. Can you please update the link to somewhere people may get the extension? Perhaps this? https://xcache.lighttpd.net/#Downloads

2019-01-28 23:11 UTC, CameronHall requested changes

2019-01-28 23:11 UTC, CameronHall commented on en/cache.md
> +| [Phalcon\Cache\Backend\Xcache](api/Phalcon_Cache_Backend_Xcache)       | Stores data in XCache.                               | [XCache](https://xcache.lighttpd.net/)     | XCache
Can you please update the link to somewhere people may get the extension? Perhaps this? https://xcache.lighttpd.net/#Downloads

2019-01-29 01:05 UTC, niden commented
I have not rewritten the cache component (still WIP). Once I do this document will be updated to the latest functionality. I belive Apc and Xcache have been deprecated for this component

2019-01-29 01:08 UTC, CameronHall commented
In that case, we can make changes to this page later on when @niden is done with the new cache component.

2019-01-29 01:08 UTC, closed without merging