Fix typo and style in sentence
phalcon/docs pull request #2498
Opened 2019-11-04 21:32 UTC by diplopito

2019-11-04 22:33 UTC, Arhell approved these changes

2019-11-05 00:49 UTC, niden requested changes

2019-11-05 00:49 UTC, niden commented on en/assets.md
> +[di-factorydefault]: api/phalcon_di@di-factorydefault
`[di-factorydefault]: api/phalcon_di#di-factorydefault`

2019-11-05 00:50 UTC, niden commented on en/assets.md
> +[di-factorydefault]: api/phalcon_di@di-factorydefault
nice catch

2019-11-23 18:46 UTC, ruudboon approved these changes

2019-11-23 18:46 UTC, merged