Update db-models-relationships.md
phalcon/docs pull request #2565
Opened 2019-12-06 21:36 UTC by ruudboon

Added wiki link

2019-12-06 21:57 UTC, niden requested changes

2019-12-06 21:57 UTC, niden commented on en/db-models-relationships.md
>  [db-normalization]: https://en.wikipedia.org/wiki/Database_normalization
Shouldn't you add this one up there like so?

[Database normalization] [db-normalization]

(without the space)

2019-12-06 22:59 UTC, Arhell approved these changes

2019-12-07 10:43 UTC, Arhell approved these changes

2019-12-07 10:50 UTC, merged