Update tutorial-rest.md
phalcon/docs pull request #2566
Opened 2019-12-06 21:43 UTC by ruudboon

Add reference to our rest api

2019-12-06 21:59 UTC, niden requested changes

2019-12-06 21:59 UTC, niden commented on en/tutorial-rest.md
> +> **NOTE**: This is just a sample application. It lacks a lot of features such as authentication, authorization, sanitization of input and error management to name a few. Please use it as a building
Can you add the alternative syntax for this? The one where we have the link at the bottom of the doc etc.

[ blah blah] [link stub here]

[link stub]: some URL

2019-12-06 22:59 UTC, Arhell approved these changes

2019-12-07 10:44 UTC, Arhell approved these changes

2019-12-07 10:50 UTC, merged