Update forms.md
phalcon/docs pull request #3130
Opened 2023-03-16 14:03 UTC by zikezhang

update out-of-date documentation.

class ```Phalcon\Forms\Element``` does not exist anymore in Phalcon 5.0.

2023-03-17 00:15 UTC, Arhell approved these changes

2023-04-28 01:08 UTC, niden requested changes

2023-04-28 01:08 UTC, niden commented on en/forms.md
> +You can also create your own elements by extending the [Phalcon\Forms\Element\AbstractElement](https://docs.phalcon.io/5.0/en/api/phalcon_forms#forms-element-abstractelement) abstract class.
Can you please change the link to this

[Phalcon\Forms\Element\AbstractElement][forms-element-abstractelement]

2023-07-03 12:56 UTC, merged

2023-07-03 12:57 UTC, niden commented
Thank you @zikezhang